# Generated by Django 5.1.3 on 2024-11-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_dealer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
