# Generated by Django 5.1.3 on 2025-01-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0002_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
