# Generated by Django 5.1.3 on 2024-11-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealerProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('social_media', models.CharField(max_length=400)),
                ('years_in_business', models.IntegerField()),
                ('pic', models.ImageField(upload_to='users/%Y/%m/%d/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
