# Generated by Django 5.1.3 on 2025-01-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0002_dealerprofilemodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
