# Generated by Django 5.1.3 on 2024-11-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0002_alter_dealerprofilemodel_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprofilemodel',
            name='pic',
            field=models.ImageField(blank=True, upload_to='profile-img/%Y/%m/%d/'),
        ),
    ]
