# Generated by Django 5.1.3 on 2024-11-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0005_alter_dealerprofilemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerprofilemodel',
            name='user',
        ),
    ]
