# Generated by Django 5.1.3 on 2025-01-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0007_alter_userprofilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile-img/%Y/%m/%d/'),
        ),
    ]
