# Generated by Django 5.1.3 on 2024-11-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0008_remove_dealerprofilemodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprofilemodel',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
