# Generated by Django 5.1.3 on 2025-01-18 00:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0008_alter_userprofilemodel_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='profile-img'),
            preserve_default=False,
        ),
    ]
