# Generated by Django 5.1.3 on 2024-11-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0009_alter_dealerprofilemodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprofilemodel',
            name='years_in_business',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
