# Generated by Django 5.1.3 on 2024-11-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0010_alter_dealerprofilemodel_years_in_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprofilemodel',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
