# Generated by Django 5.1.3 on 2024-11-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0011_alter_dealerprofilemodel_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerprofilemodel',
            name='email',
        ),
    ]
