# Generated by Django 5.1.3 on 2024-11-27 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0013_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carzz.dealerprofilemodel'),
        ),
    ]
