# Generated by Django 5.1.3 on 2024-11-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0016_carimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default=1, upload_to='car_images'),
            preserve_default=False,
        ),
    ]
