# Generated by Django 5.1.3 on 2024-11-28 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0018_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dealer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carzz.dealerprofilemodel'),
        ),
    ]
