# Generated by Django 5.1.3 on 2024-11-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0022_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(null=True),
        ),
    ]
