# Generated by Django 5.1.3 on 2024-11-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0023_alter_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
