# Generated by Django 5.1.3 on 2024-12-01 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0024_alter_car_description_alter_car_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='carimage',
            old_name='image',
            new_name='images',
        ),
    ]
