# Generated by Django 5.1.3 on 2024-12-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0027_alter_car_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
