# Generated by Django 5.1.3 on 2024-12-25 16:23

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0031_savedcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprofilemodel',
            name='pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[600, 600], upload_to='profile-img/%Y/%m/%d/'),
        ),
    ]
