# Generated by Django 5.1.3 on 2024-12-29 15:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0034_alter_car_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='car_image'),
            preserve_default=False,
        ),
    ]
