# Generated by Django 5.1.3 on 2024-12-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0036_alter_car_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
