# Generated by Django 5.1.3 on 2024-12-31 19:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carzz', '0037_alter_carimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='car_image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='car_images'),
            preserve_default=False,
        ),
    ]
